<div style="background-color:#009440; padding: 0px; background-size:cover; background-opacity:50%; border-radius:5px; height: 300px">
    <div style="margin: 5px; padding: 10px;"><h1 style="color:#00000">Geophysical Data Acquisition and Analysis</h1>
    <h4 style="color:#dddddd">LMU, 05/06 August 2019</h4>
        <h4 style="color:#dddddd">Authors: Ceri Nunn, Stefanie Donner, Alice Gabriel, Céline Hadziioannou, Stephanie Wollherr, Taufiqurrahman</h4>
    </div>
    <div style="float:right; margin: 10px; padding: 20px; background:rgba(255,255,255,0.7); width: 70%; height: 150px">
        <div style="position:relative; top:30%; transform: translateY(-50%)">
            <div style="font-size: x-large; font-weight:900; color:rgba(0,0,0,0.8); line-height:100%">P03a - Mathematical Basics: Vectors and Matrices, Vector Norms, Matrix Inversion, Determinants, Eigenvectors</div>
                    </div>
    </div>
</div>


This notebook provides some basic maths for seismic data processing and inverse problems. 
It is intended to be refreshment only.
The notebook provides some examples of the mathematics being used. We include examples of the use of the techniques in geophysics.  


Experiment with the examples. Work in groups of 
2/3, but work on your own version of the notebook


Please execute Cell 1 first:

In [1]:
# Cell 1: Preparation for programming
import warnings
warnings.filterwarnings("ignore")
%matplotlib notebook
from scipy import interpolate, signal
from obspy import *
import numpy as np
import matplotlib.pylab as plt
# plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = 8, 3

# Vectors and Matrices

## 1) Linear Vector Spaces 

For discrete linear inverse problems we will need the concept of
**linear vector spaces**. The generalization of the concept of size of a vector to matrices and function will be extremely useful for inverse problems.

<img src="images/linearvectorspaces.png" style="width: 800px; float: left;"/>




## 2) Matrix Algebra - Linear Systems 

Linear system of algebraic equations: 

<img src="images/linearvectorspaces2.png" style="width: 400px; float: left;"/>


... where the x$_1$, x$_2$, ... , x$_n$ are the unknowns ... 

In matrix form: 

<img src="images/linervectorspaces3.png" style="width: 100px; float: left;"/>

where:


<img src="images/matrixalgebra2.png" style="width: 600px; float: left;"/>


### Matrix Algebra – Vectors

<img src="images/matrixalgebra1.png" style="width: 600px; float: left;"/>



## 3) Matrices 

### Matrix Algebra 

Transpose of a Matrix: 

<img src="images/matrixalgebra3.png" style="width: 300px; float: left;"/>


### Matrix Algebra 

Symmetric matrix: 

<img src="images/matrixalgebra4.png" style="width: 150px; float: left;"/>


Identity matrix: 

<img src="images/matrixalgebra5.png" style="width: 300px; float: left;"/>


### Orthogonal Matrices 

A matric Q is said to be orthogonal if 


<img src="images/orth1.png" style="width:200px; float: left;"/>

and each column is a normal vector 


<img src="images/orth2.png" style="width: 200px; float: left;"/>

Example: 


<img src="images/orth3.png" style="width: 250px; float: left;"/>

It is easy to show that:


<img src="images/orth4.png" style="width: 300px; float: left;"/>

## 4) Matrix and Vector Norms 

How can we compare the size of vectors, matrices (and
functions!)?
For scalars it is easy (absolute value). The generalization of this
concept to vectors, matrices and functions is called a **norm**.
Formally the norm is a function from the space of vectors into
the space of scalars denoted by:

<img src="images/norm1.png" style="width: 70px; float: left;"/>

with the following properties:

<img src="images/norm2.png" style="width: 400px; float: left;"/>



We will only deal with the so-called  l$_p$ Norm.

The l$_p$ Norm for a vector **x** is defined as (p$\geq$1):

<img src="images/norm3.png" style="width: 400px; float: left;"/>


Examples: 

* for p=2 we have the ordinary Euclidian norm:

<img src="images/norm4.png" style="width: 300px; float: left;"/>

* for p=$\infty$  the definition is:

<img src="images/norm5.png" style="width: 300px; float: left;"/>


* a norm for matrices is induced via a vector norm by

<img src="images/norm6.png" style="width: 300px; float: left;"/>

* for l$_2$ this means:

<img src="images/Spectralnorm.png" style="width: 300px; float: left;"/>

In [4]:
from numpy import array, linalg, random, sqrt, inf

# From http://glowingpython.blogspot.de/2011/04/plotting-p-norm-unit-circles-with.html
# A unit circle is a circle with a radius of one

# linalg.norm(x,p) will calculate the vector norm for us
# here we plot the shape of the unit circle 

def plotUnitCircle(p):
    """ plot some 2D vectors with p-norm < 1 """
    for i in range(1000):
        x = array([random.rand()*2-1,random.rand()*2-1])
        if linalg.norm(x,p) < 1:
            plt.plot(x[0],x[1],marker='o',color='blue')
            plt.axis([-1.5, 1.5, -1.5, 1.5])

 # change plot size
plt.rcParams['figure.figsize'] = 6, 6

# We use p-norm = 2 
p = 2 # the number of the p-norm 
plotUnitCircle(p)

# put the plot size back to normal
plt.rcParams['figure.figsize'] = 8, 3

<IPython.core.display.Javascript object>

### Question 

Make sure you can understand the code. 

Plot at least one other type of L-p norm (change the p-value). What changes do you observe to the unit 'circle'. 

## 5) Matrix Algebra and Determinants 

The determinant of a square matrix A is a scalar number denoted det (A) or |A|, for example:

<img src="images/det1.png" style="width: 250px; float: left;"/>


or

<img src="images/det2.png" style="width: 600px; float: left;"/>


### Matrix Algebra - Singularity 

A square matrix is singular if det A=0.  This usually indicates problems with the system (non-uniqueness, linear dependence, degeneracy ..)

### Matrix Algebra - Inversion  


For a square and non-singular matrix **A** its inverse is defined such as:

<img src="images/inv1.png" style="width: 250px; float: left;"/>


The cofactor matrix **C** of matrix **A** is given by 

<img src="images/inv2.png" style="width: 250px; float: left;"/>

where $M_{ij}$ is the determinant of the matrix obtained by eliminating the i-th row and the j-th column of A.
The inverse of **A** is then given by:

<img src="images/inv3.png" style="width: 250px; float: left;"/>


The transponent of the co-factor matrix $A^*$ is also called **adjoint $A^+$**. We can calculate the inverse by determining the adjoint of a matrix: $\frac{adj(A)}{det(A)}$

<img src="images/defin2.png" style="width: 250px; float: left;"/>

### Matrix Algebra – Solution techniques

... the solution to a linear system of equations is the given by:

<img src="images/sol1.png" style="width: 250px; float: left;"/>

The main task in solving a linear system of equations is finding the inverse of the  coefficient matrix **A**.

Solution techniques are e.g. 

* Gauss elimination methods
* Iterative methods

A square matrix is said to be **positive definite** if for any non-zero vector **x**: 

$x^T A x > 0$






And positive definite matrices are non-singular (invertible).

### Matrices – further definitions and properties

**Determinant**

<img src="images/defin4.png" style="width: 250px; float: left;"/>

If det(**A**) = 0 , the matrix **A** does not have an inverse.

### Symmetric Matrices 

have very special properties, for example:

if **G** has m distinct eigenvalues, it can be decomposed into

<img src="images/sym2.png" style="width: 250px; float: left;"/>



**U** contains the eigenvectors of **G** as columns and **Λ** is a diagonal matrix with the distinct eigenvectors on its diagonal.

## 6) Eigenvalue problems


Eigenvectors are one of the most important tools in stress, deformation and wave problems!

"Eigen" is a German word that, in this context, may be translated into "characteristic." We saw earlier that a matrix can be written as the product of a matrix A and vector v.

It is a simple geometrical question: find me the directions in which a square matrix does not change the orientation of a vector … and find me the scaling … 

<img src="images/eigen1.png" style="width: 200px; float: left;"/>

<img src="images/eigenvaluedescription.gif" style="width: 400px; float: left;"/>
<!--Image from Wim van Drongelen, in Signal Processing for Neuroscientists, 2010.-->

In the picture above, A is a matrix. The eigenvector is v, and the eigenvalue is 7. 
Vector v is an eigenvector of A if multiplication with matrix A scales it by a constant λ without changing the direction of v. (In the rest of section we call this vector **x**) 


### Definition of eigenvectors

An eigenvector $\boldsymbol{x}$ and corrsponding eigenvalue $\lambda$ of a square matrix $\boldsymbol{A}$ satisfy
$$ \boldsymbol{A} \boldsymbol{x} = \lambda \boldsymbol{x} $$

Rearranging this expression,
$$ \left( \boldsymbol{A} - \lambda \boldsymbol{I}\right) \boldsymbol{x} = \boldsymbol{0} $$

The above equation has solutions (other than $\boldsymbol{x} = \boldsymbol{0}$) if
$$ \det \left( \boldsymbol{A} - \lambda \boldsymbol{I}\right) = 0 $$

Computing the determinant of an $n \times n$ matrix requires solution of an $n$th degree polynomial. It is known how to compute roots of polynomials up to and including degree four (e.g., see http://en.wikipedia.org/wiki/Quartic_function). For matrices with $n>4$, numerical methods must be used to compute eigenvalues and eigenvectors.


An $n \times n$ will have $n$ eigenvalue/eigenvector pairs (eigenpairs).

In [3]:
## Exercise - Calculate eigenvales/eigenvectors of a symmetric matrix

In [4]:
# Import NumPy and seed random number generator to make generated matrices deterministic
import numpy as np
np.random.seed(1)

# Create a symmetric matrix with random entries
A = np.random.rand(5, 5)
A = A + A.T
print(A)

[[ 0.83404401  0.81266309  0.41930889  0.97280008  0.94750046]
 [ 0.81266309  0.37252042  1.03078023  0.81407228  1.50707831]
 [ 0.41930889  1.03078023  0.4089045   1.43680726  0.34081177]
 [ 0.97280008  0.81407228  1.43680726  0.28077388  0.8904241 ]
 [ 0.94750046  1.50707831  0.34081177  0.8904241   1.7527783 ]]


In [5]:
# Compute eigenvectors of A
evalues, evectors = np.linalg.eig(A)

print("Eigenvalues: {}".format(evalues))
print("Eigenvectors: {}".format(evectors))

Eigenvalues: [ 4.49901636 -1.34808792 -0.66778843  0.21610602  0.94977508]
Eigenvectors: [[-0.40163425 -0.19049617  0.13563534 -0.88537464 -0.01076773]
 [-0.45887678  0.38587861  0.76218267  0.24145961  0.03611968]
 [-0.35255653 -0.62923828  0.03786448  0.30864498 -0.61892459]
 [-0.42177956  0.60360849 -0.53501774 -0.01546805 -0.41385451]
 [-0.57090098 -0.23350566 -0.33615908  0.24961576  0.66651049]]


In [6]:
print('Show some tests on the first eigenpair')
print('Testing Ax')
print(A.dot(evectors[:,4]))
print('Testing (lambda x)')
print(evalues[4]*evectors[:,4])

Show some tests on the first eigenpair
Testing Ax
[-0.01022692  0.03430557 -0.58783915 -0.3930687   0.63303505]
Testing (lambda x)
[-0.01022692  0.03430557 -0.58783915 -0.3930687   0.63303505]


## Question 

1) Which equality have we just shown for the first eigenpair?

2) How many (non-trival) eigenpairs do we have? Show the same test on the last eigenpair. 



## Acknowledgements/Further Resources: 

The practical is based on lecture notes from Heiner Igel. 

I have used many code snippets from many locations.
    
Image from Wim van Drongelen, in Signal Processing for Neuroscientists, 2010

Garth Wells: 
https://github.com/garth-wells/IA-maths-Jupyter/blob/1dff65f7a2a30471e34976e46cf80ad4e9383292/Lecture10.ipynb


